import type {
  StoryDataRecord,
  StoryFormSectionId,
} from "@/features/story-production/types/story-data.types";

export const STORY_DATA_VERSION = "1.0";

export const STORY_FORM_SECTIONS: Array<{
  id: StoryFormSectionId;
  label: string;
}> = [
  { id: "general", label: "General" },
  { id: "media", label: "Media" },
  { id: "text", label: "Text" },
  { id: "theme", label: "Theme" },
];

export const STORY_BINDING_ALIASES: Record<string, string[]> = {
  headline: ["headline"],
  subheadline: ["subheadline", "subtitle"],
  summary: ["summary", "story", "story_summary", "ai_output"],
  sub_headline_1: ["sub_headline_1"],
  sub_headline_2: ["sub_headline_2"],
  sub_headline_3: ["sub_headline_3"],
  sub_headline_4: ["sub_headline_4"],
  sub_headline_1_media_kind: ["sub_headline_1_media_kind"],
  sub_headline_2_media_kind: ["sub_headline_2_media_kind"],
  sub_headline_3_media_kind: ["sub_headline_3_media_kind"],
  sub_headline_4_media_kind: ["sub_headline_4_media_kind"],
  sub_headline_1_media: ["sub_headline_1_media"],
  sub_headline_2_media: ["sub_headline_2_media"],
  sub_headline_3_media: ["sub_headline_3_media"],
  sub_headline_4_media: ["sub_headline_4_media"],
  sub_headline_1_caption: ["sub_headline_1_caption"],
  sub_headline_2_caption: ["sub_headline_2_caption"],
  sub_headline_3_caption: ["sub_headline_3_caption"],
  sub_headline_4_caption: ["sub_headline_4_caption"],
  reporter: ["reporter", "reporter_name"],
  reporter_photo: ["reporter_photo", "image"],
  guest: ["guest", "speaker"],
  designation: ["designation"],
  location: ["location"],
  organization: ["organization"],
  place: ["place"],
  date: ["date"],
  time: ["time"],
  story_id: ["story_id"],
  category: ["category"],
  tags: ["tags"],
  priority: ["priority"],
  breaking_news: ["breaking_news"],
  live: ["live"],
  main_video: ["main_video", "video"],
  secondary_video: ["secondary_video"],
  main_image: ["main_image", "image"],
  gallery_images: ["gallery_images"],
  background_video: ["background_video"],
  background_image: ["background_image"],
  background_transition_style: ["background_transition_style"],
  background_slide_interval_ms: ["background_slide_interval_ms"],
  background_transition_ms: ["background_transition_ms"],
  background_slide_index: ["background_slide_index"],
  background_fit: ["background_fit"],
  background_autoplay: ["background_autoplay"],
  logo: ["logo", "channel_logo"],
  watermark: ["watermark"],
  voice_over: ["voice_over", "voice"],
  background_music: ["background_music", "music"],
  sound_fx: ["sound_fx"],
  quote: ["quote", "author"],
  bible_verse: ["bible_verse", "verse"],
  verse_reference: ["verse_reference", "reference"],
  ticker: ["ticker"],
  call_to_action: ["call_to_action"],
  website: ["website"],
  social_links: ["social_links"],
  theme: ["theme"],
  primary_color: ["primary_color"],
  secondary_color: ["secondary_color"],
  accent_color: ["accent_color"],
  world_map_opacity: ["world_map_opacity"],
  glow_intensity: ["glow_intensity"],
  grid_visibility: ["grid_visibility"],
  frame_border_color: ["frame_border_color"],
  frame_border_width: ["frame_border_width"],
  frame_border_radius: ["frame_border_radius"],
  frame_glass_opacity: ["frame_glass_opacity"],
  frame_shadow_strength: ["frame_shadow_strength"],
  frame_accent_color: ["frame_accent_color"],
  frame_accent_width: ["frame_accent_width"],
  video_border: ["video_border"],
  video_border_width: ["video_border_width"],
  video_corner_style: ["video_corner_style"],
  video_corner_radius: ["video_corner_radius"],
  video_mask: ["video_mask"],
  video_padding: ["video_padding"],
  video_shadow: ["video_shadow"],
  video_glass_opacity: ["video_glass_opacity"],
  video_frame_opacity: ["video_frame_opacity"],
  video_accent_color: ["video_accent_color"],
  video_accent_thickness: ["video_accent_thickness"],
  video_fit: ["video_fit"],
  video_scale: ["video_scale"],
  video_crop: ["video_crop"],
  video_safe_area: ["video_safe_area"],
  video_position_x: ["video_position_x"],
  video_position_y: ["video_position_y"],
  video_rotation: ["video_rotation"],
  video_opacity: ["video_opacity"],
  video_media_mode: ["video_media_mode"],
  video_container_state: ["video_container_state"],
  video_top_bar_visible: ["video_top_bar_visible"],
  video_top_bar_height: ["video_top_bar_height"],
  video_top_bar_color: ["video_top_bar_color"],
  video_top_bar_opacity: ["video_top_bar_opacity"],
  video_bottom_bar_visible: ["video_bottom_bar_visible"],
  video_bottom_bar_height: ["video_bottom_bar_height"],
  video_bottom_bar_color: ["video_bottom_bar_color"],
  video_bottom_bar_opacity: ["video_bottom_bar_opacity"],
  scene_title: ["scene_title"],
  video_caption: ["video_caption"],
  camera: ["camera"],
  credit: ["credit"],
  video_animation_preset: ["video_animation_preset"],
  animation_preset: ["animation_preset"],
  font_family: ["font_family"],
};

/** Maps story form field keys to primary binding variable keys. */
export const STORY_FIELD_TO_BINDING: Partial<Record<keyof StoryDataRecord, string>> = {
  headline: "headline",
  subheadline: "subheadline",
  summary: "summary",
  sub_headline_1: "sub_headline_1",
  sub_headline_2: "sub_headline_2",
  sub_headline_3: "sub_headline_3",
  sub_headline_4: "sub_headline_4",
  sub_headline_1_media_kind: "sub_headline_1_media_kind",
  sub_headline_2_media_kind: "sub_headline_2_media_kind",
  sub_headline_3_media_kind: "sub_headline_3_media_kind",
  sub_headline_4_media_kind: "sub_headline_4_media_kind",
  sub_headline_1_media: "sub_headline_1_media",
  sub_headline_2_media: "sub_headline_2_media",
  sub_headline_3_media: "sub_headline_3_media",
  sub_headline_4_media: "sub_headline_4_media",
  sub_headline_1_caption: "sub_headline_1_caption",
  sub_headline_2_caption: "sub_headline_2_caption",
  sub_headline_3_caption: "sub_headline_3_caption",
  sub_headline_4_caption: "sub_headline_4_caption",
  category: "category",
  tags: "tags",
  priority: "priority",
  breaking_news: "breaking_news",
  live: "live",
  reporter_name: "reporter",
  reporter_photo: "reporter_photo",
  designation: "designation",
  location: "location",
  organization: "organization",
  place: "place",
  date: "date",
  time: "time",
  story_id: "story_id",
  main_video: "main_video",
  secondary_video: "secondary_video",
  main_image: "main_image",
  gallery_images: "gallery_images",
  background_video: "background_video",
  background_image: "background_image",
  background_transition_style: "background_transition_style",
  background_slide_interval_ms: "background_slide_interval_ms",
  background_transition_ms: "background_transition_ms",
  background_slide_index: "background_slide_index",
  background_fit: "background_fit",
  background_autoplay: "background_autoplay",
  logo: "logo",
  watermark: "watermark",
  voice_over: "voice_over",
  background_music: "background_music",
  sound_fx: "sound_fx",
  optional_info_image: "optional_info_image",
  optional_info_image_3: "optional_info_image_3",
  optional_info_transition_style: "optional_info_transition_style",
  optional_info_slide_interval_ms: "optional_info_slide_interval_ms",
  optional_info_transition_ms: "optional_info_transition_ms",
  optional_info_slide_index: "optional_info_slide_index",
  optional_info_text: "optional_info_text",
  optional_info_text_3: "optional_info_text_3",
  quote: "quote",
  bible_verse: "bible_verse",
  verse_reference: "verse_reference",
  ticker: "ticker",
  call_to_action: "call_to_action",
  website: "website",
  social_links: "social_links",
  theme: "theme",
  primary_color: "primary_color",
  secondary_color: "secondary_color",
  accent_color: "accent_color",
  world_map_opacity: "world_map_opacity",
  glow_intensity: "glow_intensity",
  grid_visibility: "grid_visibility",
  frame_border_color: "frame_border_color",
  frame_border_width: "frame_border_width",
  frame_border_radius: "frame_border_radius",
  frame_glass_opacity: "frame_glass_opacity",
  frame_shadow_strength: "frame_shadow_strength",
  frame_accent_color: "frame_accent_color",
  frame_accent_width: "frame_accent_width",
  video_border: "video_border",
  video_border_width: "video_border_width",
  video_corner_style: "video_corner_style",
  video_corner_radius: "video_corner_radius",
  video_mask: "video_mask",
  video_padding: "video_padding",
  video_shadow: "video_shadow",
  video_glass_opacity: "video_glass_opacity",
  video_frame_opacity: "video_frame_opacity",
  video_accent_color: "video_accent_color",
  video_accent_thickness: "video_accent_thickness",
  video_fit: "video_fit",
  video_scale: "video_scale",
  video_crop: "video_crop",
  video_safe_area: "video_safe_area",
  video_position_x: "video_position_x",
  video_position_y: "video_position_y",
  video_rotation: "video_rotation",
  video_opacity: "video_opacity",
  video_media_mode: "video_media_mode",
  video_container_state: "video_container_state",
  video_top_bar_visible: "video_top_bar_visible",
  video_top_bar_height: "video_top_bar_height",
  video_top_bar_color: "video_top_bar_color",
  video_top_bar_opacity: "video_top_bar_opacity",
  video_bottom_bar_visible: "video_bottom_bar_visible",
  video_bottom_bar_height: "video_bottom_bar_height",
  video_bottom_bar_color: "video_bottom_bar_color",
  video_bottom_bar_opacity: "video_bottom_bar_opacity",
  scene_title: "scene_title",
  video_caption: "video_caption",
  camera: "camera",
  credit: "credit",
  video_animation_preset: "video_animation_preset",
  animation_preset: "animation_preset",
  font_family: "font_family",
};

export const GENERAL_FORM_FIELDS: Array<{
  key: keyof StoryDataRecord;
  label: string;
  type: "text" | "textarea" | "toggle";
}> = [
  { key: "headline", label: "Headline", type: "text" },
  { key: "sub_headline_1", label: "Sub Headline 1", type: "text" },
  { key: "sub_headline_2", label: "Sub Headline 2", type: "text" },
  { key: "sub_headline_3", label: "Sub Headline 3", type: "text" },
  { key: "sub_headline_4", label: "Sub Headline 4", type: "text" },
  { key: "category", label: "Category", type: "text" },
  { key: "tags", label: "Tags", type: "text" },
  { key: "priority", label: "Priority", type: "text" },
  { key: "breaking_news", label: "Breaking News", type: "toggle" },
  { key: "live", label: "LIVE", type: "toggle" },
  { key: "reporter_name", label: "Reporter Name", type: "text" },
  { key: "reporter_photo", label: "Reporter Photo URL", type: "text" },
  { key: "designation", label: "Designation", type: "text" },
  { key: "location", label: "Location", type: "text" },
  { key: "organization", label: "Organization", type: "text" },
  { key: "place", label: "Place", type: "text" },
  { key: "date", label: "Date", type: "text" },
  { key: "time", label: "Time", type: "text" },
  { key: "story_id", label: "Story ID", type: "text" },
];

export const MEDIA_FORM_FIELDS: Array<{
  key: keyof StoryDataRecord;
  label: string;
  bindingToken: string;
}> = [
  { key: "main_video", label: "Main Video", bindingToken: "{{main_video}}" },
  { key: "secondary_video", label: "Secondary Video", bindingToken: "{{secondary_video}}" },
  { key: "main_image", label: "Main Image", bindingToken: "{{main_image}}" },
  { key: "gallery_images", label: "Gallery Images", bindingToken: "{{gallery_images}}" },
  { key: "background_video", label: "Background Slides", bindingToken: "{{background_video}}" },
  { key: "background_image", label: "Background Image", bindingToken: "{{background_image}}" },
  { key: "logo", label: "Logo", bindingToken: "{{channel_logo}}" },
  { key: "watermark", label: "Watermark", bindingToken: "{{watermark}}" },
  { key: "voice_over", label: "Voice Over", bindingToken: "{{voice}}" },
  { key: "background_music", label: "Background Music", bindingToken: "{{music}}" },
  { key: "sound_fx", label: "Sound FX", bindingToken: "{{sound_fx}}" },
  {
    key: "optional_info_image",
    label: "Optional Info Image",
    bindingToken: "{{optional_info_image}}",
  },
  {
    key: "optional_info_image_3",
    label: "Optional Info Image 3",
    bindingToken: "{{optional_info_image_3}}",
  },
  {
    key: "optional_info_transition_style",
    label: "Optional Info Transition Style",
    bindingToken: "{{optional_info_transition_style}}",
  },
  {
    key: "optional_info_slide_interval_ms",
    label: "Optional Info Slide Interval (ms)",
    bindingToken: "{{optional_info_slide_interval_ms}}",
  },
  {
    key: "optional_info_transition_ms",
    label: "Optional Info Transition Duration (ms)",
    bindingToken: "{{optional_info_transition_ms}}",
  },
  {
    key: "optional_info_slide_index",
    label: "Optional Info Slide Index",
    bindingToken: "{{optional_info_slide_index}}",
  },
];

export const TEXT_FORM_FIELDS: Array<{
  key: keyof StoryDataRecord;
  label: string;
  type: "text" | "textarea";
  bindingToken: string;
}> = [
  { key: "quote", label: "Quote", type: "textarea", bindingToken: "{{quote}}" },
  { key: "bible_verse", label: "Bible Verse", type: "textarea", bindingToken: "{{verse}}" },
  { key: "verse_reference", label: "Verse Reference", type: "text", bindingToken: "{{reference}}" },
  {
    key: "optional_info_text",
    label: "Optional Info Text",
    type: "textarea",
    bindingToken: "{{optional_info_text}}",
  },
  {
    key: "optional_info_text_3",
    label: "Optional Info Text 3",
    type: "textarea",
    bindingToken: "{{optional_info_text_3}}",
  },
  { key: "ticker", label: "Ticker", type: "text", bindingToken: "{{ticker}}" },
  { key: "call_to_action", label: "Call To Action", type: "text", bindingToken: "{{call_to_action}}" },
  { key: "website", label: "Website", type: "text", bindingToken: "{{website}}" },
  { key: "social_links", label: "Social Links", type: "text", bindingToken: "{{social_links}}" },
  { key: "place", label: "Place", type: "text", bindingToken: "{{place}}" },
];

export const THEME_FORM_FIELDS: Array<{
  key: keyof StoryDataRecord;
  label: string;
  type: "text" | "color" | "toggle";
}> = [
  { key: "theme", label: "Theme", type: "text" },
  { key: "primary_color", label: "Primary Color", type: "color" },
  { key: "secondary_color", label: "Secondary Color", type: "color" },
  { key: "accent_color", label: "Accent Color", type: "color" },
  { key: "world_map_opacity", label: "World Map Opacity", type: "text" },
  { key: "glow_intensity", label: "Glow Intensity", type: "text" },
  { key: "grid_visibility", label: "Grid Visibility", type: "toggle" },
  { key: "frame_border_color", label: "Border Color", type: "color" },
  { key: "frame_border_width", label: "Border Width", type: "text" },
  { key: "frame_border_radius", label: "Border Radius", type: "text" },
  { key: "frame_glass_opacity", label: "Glass Opacity", type: "text" },
  { key: "frame_shadow_strength", label: "Shadow Strength", type: "text" },
  { key: "frame_accent_color", label: "Accent Color", type: "color" },
  { key: "frame_accent_width", label: "Accent Width", type: "text" },
  { key: "video_border", label: "Video Border", type: "color" },
  { key: "video_border_width", label: "Border Width", type: "text" },
  { key: "video_corner_radius", label: "Corner Radius", type: "text" },
  { key: "video_padding", label: "Padding", type: "text" },
  { key: "video_shadow", label: "Inner Shadow", type: "text" },
  { key: "video_glass_opacity", label: "Glass Opacity", type: "text" },
  { key: "video_frame_opacity", label: "Frame Opacity", type: "text" },
  { key: "video_accent_color", label: "Accent Color", type: "color" },
  { key: "video_accent_thickness", label: "Accent Thickness", type: "text" },
  { key: "video_fit", label: "Video Fit", type: "text" },
  { key: "video_scale", label: "Video Scale", type: "text" },
  { key: "video_crop", label: "Video Crop", type: "text" },
  { key: "video_safe_area", label: "Safe Area", type: "text" },
  { key: "video_media_mode", label: "Media Mode", type: "text" },
  { key: "video_container_state", label: "Video State", type: "text" },
  { key: "video_animation_preset", label: "Animation Preset", type: "text" },
  { key: "font_family", label: "Malayalam Font", type: "text" },
];
