import { definePreset } from "@/features/scene-composer/lib/motion-presets/define-preset";
import type { MotionPreset } from "@/features/scene-composer/lib/motion-presets/types";

export const BASIC_PRESETS: MotionPreset[] = [
  definePreset({
    id: "basic.fade-in",
    name: "Fade In",
    category: "basic",
    description: "Soft opacity entrance",
    durationMs: 450,
    tags: ["fade", "entrance", "opacity"],
    icon: "fade",
    motion: {
      entrance: { type: "fade_in", durationMs: 450, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 350, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.fade-out",
    name: "Fade Out",
    category: "basic",
    description: "Soft opacity exit emphasis",
    durationMs: 400,
    tags: ["fade", "exit", "opacity"],
    icon: "fade",
    motion: {
      entrance: { type: "none", durationMs: 0, delayMs: 0, easing: "linear" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 400, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.slide-left",
    name: "Slide Left",
    category: "basic",
    description: "Enter from the left",
    durationMs: 500,
    tags: ["slide", "left", "entrance"],
    icon: "slide",
    motion: {
      entrance: { type: "slide_left", durationMs: 500, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_left", durationMs: 350, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.slide-right",
    name: "Slide Right",
    category: "basic",
    description: "Enter from the right",
    durationMs: 500,
    tags: ["slide", "right", "entrance"],
    icon: "slide",
    motion: {
      entrance: { type: "slide_right", durationMs: 500, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_right", durationMs: 350, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.slide-up",
    name: "Slide Up",
    category: "basic",
    description: "Rise into frame",
    durationMs: 480,
    tags: ["slide", "up", "entrance"],
    icon: "slide",
    motion: {
      entrance: { type: "slide_up", durationMs: 480, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_down", durationMs: 340, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.slide-down",
    name: "Slide Down",
    category: "basic",
    description: "Drop into frame",
    durationMs: 480,
    tags: ["slide", "down", "entrance"],
    icon: "slide",
    motion: {
      entrance: { type: "slide_down", durationMs: 480, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_up", durationMs: 340, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.scale-in",
    name: "Scale In",
    category: "basic",
    description: "Scale up with fade",
    durationMs: 450,
    tags: ["scale", "entrance"],
    icon: "scale",
    motion: {
      entrance: { type: "scale_in", durationMs: 450, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "scale_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.scale-out",
    name: "Scale Out",
    category: "basic",
    description: "Scale down exit",
    durationMs: 380,
    tags: ["scale", "exit"],
    icon: "scale",
    motion: {
      entrance: { type: "none", durationMs: 0, delayMs: 0, easing: "linear" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "scale_out", durationMs: 380, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.zoom",
    name: "Zoom",
    category: "basic",
    description: "Overshoot zoom settle",
    durationMs: 520,
    tags: ["zoom", "entrance"],
    icon: "zoom",
    motion: {
      entrance: { type: "zoom", durationMs: 520, delayMs: 0, easing: "ease_out" },
      idle: { type: "slow_zoom", speed: 0.35, loop: true },
      exit: { type: "scale_out", durationMs: 360, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.pop",
    name: "Pop",
    category: "basic",
    description: "Snappy scale pop-in",
    durationMs: 320,
    tags: ["pop", "scale", "snap"],
    icon: "pop",
    motion: {
      entrance: { type: "scale_in", durationMs: 280, delayMs: 0, easing: "cubic" },
      idle: { type: "pulse", speed: 0.8, loop: false },
      exit: { type: "scale_out", durationMs: 240, delayMs: 0, easing: "ease_in" },
      speed: 1.15,
    },
  }),
  definePreset({
    id: "basic.opacity",
    name: "Opacity",
    category: "basic",
    description: "Linear opacity crossfade",
    durationMs: 500,
    tags: ["opacity", "fade"],
    icon: "opacity",
    motion: {
      entrance: { type: "opacity", durationMs: 500, delayMs: 0, easing: "linear" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "opacity", durationMs: 500, delayMs: 0, easing: "linear" },
    },
  }),
  definePreset({
    id: "basic.idle-swell",
    name: "Idle Swell",
    category: "basic",
    description: "Soft fade-in with breathing scale swell",
    durationMs: 450,
    tags: ["swell", "idle", "breathe", "scale"],
    icon: "scale",
    motion: {
      entrance: { type: "fade_in", durationMs: 400, delayMs: 0, easing: "ease_out" },
      idle: { type: "swell", speed: 0.75, loop: true },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.idle-orbit",
    name: "Idle Orbit Path",
    category: "basic",
    description: "Continuous circular loop around the home position",
    durationMs: 450,
    tags: ["orbit", "path", "idle", "loop", "circle"],
    icon: "float",
    motion: {
      entrance: { type: "fade_in", durationMs: 400, delayMs: 0, easing: "ease_out" },
      idle: {
        type: "orbit",
        speed: 1,
        loop: true,
        pathRadius: 56,
        offset: 0,
      },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.idle-swivel",
    name: "Idle Swivel 3D",
    category: "basic",
    description: "Gentle back-and-forth 3D tilt (Y axis)",
    durationMs: 450,
    tags: ["swivel", "rotate", "idle", "3d", "y-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "fade_in", durationMs: 400, delayMs: 0, easing: "ease_out" },
      idle: { type: "swivel", speed: 0.85, loop: true, axis: "y", amplitude: 40 },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.idle-rotate-y",
    name: "Idle Rotate Y",
    category: "basic",
    description: "Continuous 3D spin around the Y axis",
    durationMs: 450,
    tags: ["rotate", "idle", "spin", "3d", "y-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "fade_in", durationMs: 400, delayMs: 0, easing: "ease_out" },
      idle: { type: "rotate", speed: 0.7, loop: true, axis: "y" },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.idle-rotate-x",
    name: "Idle Rotate X",
    category: "basic",
    description: "Continuous 3D tumble around the X axis",
    durationMs: 450,
    tags: ["rotate", "idle", "spin", "3d", "x-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "fade_in", durationMs: 400, delayMs: 0, easing: "ease_out" },
      idle: { type: "rotate", speed: 0.7, loop: true, axis: "x" },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "basic.idle-rotate-z",
    name: "Idle Rotate Z",
    category: "basic",
    description: "Continuous spin around the Z axis (screen plane)",
    durationMs: 450,
    tags: ["rotate", "idle", "spin", "3d", "z-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "fade_in", durationMs: 400, delayMs: 0, easing: "ease_out" },
      idle: { type: "rotate", speed: 0.7, loop: true, axis: "z" },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
];
