import { definePreset } from "@/features/scene-composer/lib/motion-presets/define-preset";
import type { MotionPreset } from "@/features/scene-composer/lib/motion-presets/types";

export const PROFESSIONAL_NEWS_PRESETS: MotionPreset[] = [
  definePreset({
    id: "news.header-reveal",
    name: "News Header Reveal",
    category: "professional_news",
    description: "Header drops in with soft fade",
    durationMs: 520,
    tags: ["header", "news", "slide"],
    icon: "header",
    motion: {
      entrance: { type: "slide_down", durationMs: 500, delayMs: 80, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_up", durationMs: 340, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "news.headline-expand",
    name: "Headline Expand",
    category: "professional_news",
    description: "Headline rises and settles",
    durationMs: 560,
    tags: ["headline", "expand", "text"],
    icon: "text",
    motion: {
      entrance: { type: "slide_up", durationMs: 520, delayMs: 120, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 300, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "news.reporter-card-slide",
    name: "Reporter Card Slide",
    category: "professional_news",
    description: "Reporter plate slides from left",
    durationMs: 580,
    tags: ["reporter", "card", "slide"],
    icon: "reporter",
    motion: {
      entrance: { type: "slide_left", durationMs: 550, delayMs: 160, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_left", durationMs: 360, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "news.video-frame-reveal",
    name: "Video Frame Reveal",
    category: "professional_news",
    description: "Scale + fade video frame open",
    durationMs: 620,
    tags: ["video", "frame", "reveal"],
    icon: "video",
    motion: {
      entrance: { type: "scale_in", durationMs: 600, delayMs: 140, easing: "ease_out" },
      idle: { type: "slow_zoom", speed: 0.3, loop: true },
      exit: { type: "scale_out", durationMs: 400, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "news.breaking-flash",
    name: "Breaking Flash",
    category: "professional_news",
    description: "Urgent flash pulse entrance",
    durationMs: 380,
    tags: ["breaking", "flash", "pulse"],
    icon: "flash",
    motion: {
      entrance: { type: "opacity", durationMs: 220, delayMs: 0, easing: "cubic" },
      idle: { type: "pulse", speed: 1.6, loop: true },
      exit: { type: "fade_out", durationMs: 260, delayMs: 0, easing: "ease_in" },
      speed: 1.2,
    },
  }),
  definePreset({
    id: "news.live-indicator-pulse",
    name: "Live Indicator Pulse",
    category: "professional_news",
    description: "Continuous live badge pulse",
    durationMs: 400,
    tags: ["live", "pulse", "badge"],
    icon: "live",
    motion: {
      entrance: { type: "fade_in", durationMs: 280, delayMs: 0, easing: "ease_out" },
      idle: { type: "pulse", speed: 1.2, loop: true },
      exit: { type: "fade_out", durationMs: 220, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "news.info-panel-reveal",
    name: "Information Panel Reveal",
    category: "professional_news",
    description: "Lower info panel rises in",
    durationMs: 500,
    tags: ["panel", "info", "reveal"],
    icon: "panel",
    motion: {
      entrance: { type: "slide_up", durationMs: 480, delayMs: 200, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_down", durationMs: 340, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "news.side-panel-expand",
    name: "Side Panel Expand",
    category: "professional_news",
    description: "Left rail expands from edge",
    durationMs: 540,
    tags: ["side", "panel", "expand"],
    icon: "panel",
    motion: {
      entrance: { type: "wipe_left", durationMs: 520, delayMs: 100, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "wipe", durationMs: 360, delayMs: 0, easing: "ease_in" },
    },
  }),
];
