import { definePreset } from "@/features/scene-composer/lib/motion-presets/define-preset";
import type { MotionPreset } from "@/features/scene-composer/lib/motion-presets/types";

export const TEXT_PRESETS: MotionPreset[] = [
  definePreset({
    id: "text.typewriter",
    name: "Typewriter",
    category: "text",
    description: "Staggered opacity reveal (typewriter feel)",
    durationMs: 900,
    tags: ["text", "typewriter", "chars"],
    icon: "text",
    motion: {
      entrance: { type: "opacity", durationMs: 900, delayMs: 40, easing: "linear" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "text.word-reveal",
    name: "Word Reveal",
    category: "text",
    description: "Word-block slide reveal",
    durationMs: 640,
    tags: ["text", "word", "reveal"],
    icon: "text",
    motion: {
      entrance: { type: "slide_up", durationMs: 620, delayMs: 80, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 300, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "text.character-reveal",
    name: "Character Reveal",
    category: "text",
    description: "Fine character-like fade",
    durationMs: 760,
    tags: ["text", "character", "reveal"],
    icon: "text",
    motion: {
      entrance: { type: "fade_in", durationMs: 740, delayMs: 60, easing: "ease_in_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "opacity", durationMs: 360, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "text.blur-reveal",
    name: "Blur Reveal",
    category: "text",
    description: "Soft focus settle via scale fade",
    durationMs: 580,
    tags: ["text", "blur", "reveal"],
    icon: "blur",
    motion: {
      entrance: { type: "zoom", durationMs: 560, delayMs: 40, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 340, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "text.mask-reveal",
    name: "Mask Reveal",
    category: "text",
    description: "Horizontal mask text reveal",
    durationMs: 600,
    tags: ["text", "mask", "reveal"],
    icon: "mask",
    motion: {
      entrance: { type: "mask_reveal", durationMs: 580, delayMs: 40, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "mask_close", durationMs: 360, delayMs: 0, easing: "ease_in" },
    },
  }),
];

export const VIDEO_PRESETS: MotionPreset[] = [
  definePreset({
    id: "video.zoom",
    name: "Video Zoom",
    category: "video",
    description: "Video frame zoom with slow Ken Burns",
    durationMs: 620,
    tags: ["video", "zoom"],
    icon: "video",
    motion: {
      entrance: { type: "zoom", durationMs: 600, delayMs: 80, easing: "ease_out" },
      idle: { type: "slow_zoom", speed: 0.35, loop: true },
      exit: { type: "scale_out", durationMs: 400, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "video.fade",
    name: "Video Fade",
    category: "video",
    description: "Video opacity fade",
    durationMs: 520,
    tags: ["video", "fade"],
    icon: "video",
    motion: {
      entrance: { type: "fade_in", durationMs: 500, delayMs: 60, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 400, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "video.slide",
    name: "Video Slide",
    category: "video",
    description: "Video slides from right",
    durationMs: 560,
    tags: ["video", "slide"],
    icon: "video",
    motion: {
      entrance: { type: "slide_right", durationMs: 540, delayMs: 80, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_left", durationMs: 380, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "video.mask-reveal",
    name: "Video Mask Reveal",
    category: "video",
    description: "Masked video open",
    durationMs: 640,
    tags: ["video", "mask"],
    icon: "mask",
    motion: {
      entrance: { type: "mask_reveal", durationMs: 620, delayMs: 60, easing: "ease_out" },
      idle: { type: "slow_zoom", speed: 0.25, loop: true },
      exit: { type: "mask_close", durationMs: 420, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "video.wipe",
    name: "Video Wipe",
    category: "video",
    description: "Broadcast wipe into video",
    durationMs: 540,
    tags: ["video", "wipe"],
    icon: "wipe",
    motion: {
      entrance: { type: "wipe_left", durationMs: 520, delayMs: 40, easing: "ease_in_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "wipe", durationMs: 400, delayMs: 0, easing: "ease_in" },
    },
  }),
];

export const BACKGROUND_PRESETS: MotionPreset[] = [
  definePreset({
    id: "bg.gradient-shift",
    name: "Gradient Shift",
    category: "background",
    description: "Soft background fade with parallax idle",
    durationMs: 900,
    tags: ["background", "gradient"],
    icon: "bg",
    motion: {
      entrance: { type: "fade_in", durationMs: 900, delayMs: 0, easing: "ease_out" },
      idle: { type: "parallax", speed: 0.2, loop: true },
      exit: { type: "fade_out", durationMs: 600, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "bg.particle-drift",
    name: "Particle Drift",
    category: "background",
    description: "Floating atmospheric drift",
    durationMs: 800,
    tags: ["background", "particles", "drift"],
    icon: "bg",
    motion: {
      entrance: { type: "fade_in", durationMs: 700, delayMs: 0, easing: "ease_out" },
      idle: { type: "float", speed: 0.45, loop: true },
      exit: { type: "fade_out", durationMs: 500, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "bg.light-sweep",
    name: "Light Sweep",
    category: "background",
    description: "Glow sweep across plate",
    durationMs: 760,
    tags: ["background", "light", "glow"],
    icon: "glow",
    motion: {
      entrance: { type: "wipe_left", durationMs: 720, delayMs: 0, easing: "ease_in_out" },
      idle: { type: "glow", speed: 0.55, loop: true },
      exit: { type: "fade_out", durationMs: 480, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "bg.floating-shapes",
    name: "Floating Shapes",
    category: "background",
    description: "Slow float with soft fade",
    durationMs: 850,
    tags: ["background", "float", "shapes"],
    icon: "bg",
    motion: {
      entrance: { type: "fade_in", durationMs: 800, delayMs: 0, easing: "ease_out" },
      idle: { type: "float", speed: 0.35, loop: true },
      exit: { type: "fade_out", durationMs: 520, delayMs: 0, easing: "ease_in" },
    },
  }),
];
