import { definePreset } from "@/features/scene-composer/lib/motion-presets/define-preset";
import type { MotionPreset } from "@/features/scene-composer/lib/motion-presets/types";

export const TRANSITION_PRESETS: MotionPreset[] = [
  definePreset({
    id: "tr.scene-fade",
    name: "Scene Fade",
    category: "transitions",
    kind: "transition",
    description: "Full layer dissolve",
    durationMs: 700,
    tags: ["transition", "fade", "scene"],
    icon: "transition",
    motion: {
      entrance: { type: "fade_in", durationMs: 700, delayMs: 0, easing: "ease_in_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 700, delayMs: 0, easing: "ease_in_out" },
    },
  }),
  definePreset({
    id: "tr.push",
    name: "Push",
    category: "transitions",
    kind: "transition",
    description: "Push from right",
    durationMs: 560,
    tags: ["transition", "push"],
    icon: "transition",
    motion: {
      entrance: { type: "slide_right", durationMs: 560, delayMs: 0, easing: "ease_in_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_left", durationMs: 560, delayMs: 0, easing: "ease_in_out" },
    },
  }),
  definePreset({
    id: "tr.slide",
    name: "Slide",
    category: "transitions",
    kind: "transition",
    description: "Horizontal slide transition",
    durationMs: 500,
    tags: ["transition", "slide"],
    icon: "slide",
    motion: {
      entrance: { type: "slide_left", durationMs: 500, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "slide_right", durationMs: 500, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "tr.zoom",
    name: "Zoom",
    category: "transitions",
    kind: "transition",
    description: "Zoom transition through frame",
    durationMs: 540,
    tags: ["transition", "zoom"],
    icon: "zoom",
    motion: {
      entrance: { type: "zoom", durationMs: 540, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "scale_out", durationMs: 480, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "tr.cross-dissolve",
    name: "Cross Dissolve",
    category: "transitions",
    kind: "transition",
    description: "Classic cross dissolve",
    durationMs: 800,
    tags: ["transition", "dissolve"],
    icon: "fade",
    motion: {
      entrance: { type: "opacity", durationMs: 800, delayMs: 0, easing: "linear" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "opacity", durationMs: 800, delayMs: 0, easing: "linear" },
    },
  }),
  definePreset({
    id: "tr.broadcast-wipe",
    name: "Broadcast Wipe",
    category: "transitions",
    kind: "transition",
    description: "Broadcast wipe left",
    durationMs: 560,
    tags: ["transition", "wipe", "broadcast"],
    icon: "wipe",
    motion: {
      entrance: { type: "wipe_left", durationMs: 560, delayMs: 0, easing: "ease_in_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "wipe", durationMs: 560, delayMs: 0, easing: "ease_in_out" },
    },
  }),
];

export const LOGO_PRESETS: MotionPreset[] = [
  definePreset({
    id: "logo.fade",
    name: "Fade Logo",
    category: "logo",
    description: "Simple logo fade",
    durationMs: 420,
    tags: ["logo", "fade"],
    icon: "logo",
    motion: {
      entrance: { type: "fade_in", durationMs: 420, delayMs: 60, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "fade_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.rotate-reveal",
    name: "Rotate Reveal",
    category: "logo",
    description: "Scale settle with glow idle",
    durationMs: 560,
    tags: ["logo", "rotate", "reveal"],
    icon: "logo",
    motion: {
      entrance: { type: "scale_in", durationMs: 540, delayMs: 40, easing: "cubic" },
      idle: { type: "glow", speed: 0.7, loop: true },
      exit: { type: "scale_out", durationMs: 360, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.slow-swell",
    name: "Slow Swell",
    category: "logo",
    description: "Logo fade-in with gentle breathing swell",
    durationMs: 480,
    tags: ["logo", "swell", "breathe", "idle"],
    icon: "scale",
    motion: {
      entrance: { type: "fade_in", durationMs: 420, delayMs: 40, easing: "ease_out" },
      idle: { type: "swell", speed: 0.45, loop: true },
      exit: { type: "fade_out", durationMs: 300, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.swivel-y",
    name: "Swivel Y",
    category: "logo",
    description: "Logo gently turns on the Y axis (3D card)",
    durationMs: 480,
    tags: ["logo", "swivel", "rotate", "3d", "y-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "fade_in", durationMs: 420, delayMs: 40, easing: "ease_out" },
      idle: { type: "swivel", speed: 0.65, loop: true, axis: "y", amplitude: 40 },
      exit: { type: "fade_out", durationMs: 300, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.rotate-y",
    name: "Rotate Y",
    category: "logo",
    description: "Logo continuously spins on the Y axis",
    durationMs: 520,
    tags: ["logo", "rotate", "spin", "3d", "y-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "scale_in", durationMs: 500, delayMs: 0, easing: "ease_out" },
      idle: { type: "rotate", speed: 0.55, loop: true, axis: "y" },
      exit: { type: "scale_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.rotate-x",
    name: "Rotate X",
    category: "logo",
    description: "Logo tumbles on the X axis",
    durationMs: 520,
    tags: ["logo", "rotate", "spin", "3d", "x-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "scale_in", durationMs: 500, delayMs: 0, easing: "ease_out" },
      idle: { type: "rotate", speed: 0.55, loop: true, axis: "x" },
      exit: { type: "scale_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.rotate-z",
    name: "Rotate Z",
    category: "logo",
    description: "Logo spins on the Z axis",
    durationMs: 520,
    tags: ["logo", "rotate", "spin", "3d", "z-axis"],
    icon: "rotate",
    motion: {
      entrance: { type: "scale_in", durationMs: 500, delayMs: 0, easing: "ease_out" },
      idle: { type: "rotate", speed: 0.55, loop: true, axis: "z" },
      exit: { type: "scale_out", durationMs: 320, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.scale-reveal",
    name: "Scale Reveal",
    category: "logo",
    description: "Logo scales into place",
    durationMs: 480,
    tags: ["logo", "scale"],
    icon: "scale",
    motion: {
      entrance: { type: "scale_in", durationMs: 460, delayMs: 0, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "scale_out", durationMs: 300, delayMs: 0, easing: "ease_in" },
    },
  }),
  definePreset({
    id: "logo.corner-reveal",
    name: "Corner Reveal",
    category: "logo",
    description: "Wipe-in corner bug",
    durationMs: 440,
    tags: ["logo", "corner", "bug"],
    icon: "logo",
    motion: {
      entrance: { type: "wipe_right", durationMs: 420, delayMs: 80, easing: "ease_out" },
      idle: { type: "none", speed: 1, loop: true },
      exit: { type: "wipe", durationMs: 300, delayMs: 0, easing: "ease_in" },
    },
  }),
];
